[tool.poetry]
name = "spark-cluster-optimiser"
version = "0.1.0"
description = "Optimizes AWS EMR instance selection for Spark jobs."
authors = ["Amar Prakash Pandey <@amarlearning>"]
readme = "README.md"
packages = [{include = "spark_cluster_optimiser"}]

[tool.poetry.dependencies]
python = "^3.10.14"
requests = "^2.32.3"
diskcache = "^5.6.3"
appdirs = "^1.4.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
black = "^23.1.0"
isort = "^5.10.1"
pre-commit = "^4.0.1"
types-requests = "^2.32.0.20241016"

[tool.black]
line-length = 80
target-version = ['py310']

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
