name: Performance Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'spot_optimizer/**'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
        
    - name: Run benchmarks
      run: |
        mkdir -p tests/resources
        chmod +x tests/performance/run_benchmark.sh
        ./tests/performance/run_benchmark.sh
        cat tests/performance/benchmark_queries.log
